name: Build Flutter Container

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version tag'
        required: false
        default: 'latest'

jobs:
  build:
    uses: ./.github/workflows/reusable-build-container.yml
    with:
      publish_target: publish-flutter
      version: ${{ inputs.version || 'latest' }}
    permissions:
      contents: read
      packages: write
